### ISSUE TITLE
Не работает с proxy

### ISSUE THREAD

**Issue by aksenov** [tkachenko1503/solar-test#1]
Из-за [особенностей httpkit](https://github.com/stylefruits/gniazdo/issues/19)
upd. [ссылка непосредственно на багу в httpkit](https://github.com/http-kit/http-kit/issues/75)

```
SEVERE: #error {
 :cause В соединении отказано
 :via
 [{:type java.net.ConnectException
   :message В соединении отказано
   :at [sun.nio.ch.SocketChannelImpl checkConnect SocketChannelImpl.java -2]}]
 :trace
 [[sun.nio.ch.SocketChannelImpl checkConnect SocketChannelImpl.java -2]
  [sun.nio.ch.SocketChannelImpl finishConnect SocketChannelImpl.java 717]
  [org.httpkit.client.HttpClient finishConnect HttpClient.java 342]
  [org.httpkit.client.HttpClient run HttpClient.java 424]
  [java.lang.Thread run Thread.java 745]]}
мар 15, 2017 3:43:27 PM clojure.tools.logging$eval9116$fn__9120 invoke
INFO: --STOP collecting
Exception in thread "async-dispatch-2" java.lang.Error: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at clojure.xml$startparse_sax.invokeStatic(xml.clj:76)
	at clojure.xml$startparse_sax.invoke(xml.clj:75)
	at clojure.xml$parse.invokeStatic(xml.clj:92)
	at clojure.xml$parse.invoke(xml.clj:78)
	at clojure.xml$parse.invokeStatic(xml.clj:86)
	at clojure.xml$parse.invoke(xml.clj:78)
	at ariane.core$parse.invokeStatic(core.clj:18)
	at ariane.core$parse.invoke(core.clj:15)
	at clojure.core$map$fn__4785.invoke(core.clj:2644)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$map$fn__4785.invoke(core.clj:2637)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$seq__4357.invoke(core.clj:137)
	at clojure.core$tree_seq$walk__5273$fn__5274.invoke(core.clj:4763)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.LazySeq.more(LazySeq.java:85)
	at clojure.lang.RT.more(RT.java:697)
	at clojure.core$rest__4343.invokeStatic(core.clj:73)
	at clojure.core$flatten.invokeStatic(core.clj:6850)
	at clojure.core$flatten.invoke(core.clj:6850)
	at solar.core$calc_statistic.invokeStatic(core.clj:153)
	at solar.core$calc_statistic.invoke(core.clj:145)
	at solar.core$get_domains_statistics$fn__13610$state_machine__5907__auto____13623$fn__13625.invoke(core.clj:167)
	at solar.core$get_domains_statistics$fn__13610$state_machine__5907__auto____13623.invoke(core.clj:164)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async$ioc_alts_BANG_$fn__6110.invoke(async.clj:384)
	at clojure.core.async$do_alts$fn__6056$fn__6059.invoke(async.clj:253)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__792.invoke(channels.clj:135)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

```

**Comment by tkachenko1503** [comment]
а в каком случае будет появляться эта ошибка?
я сейчас запускаю код в repl и этой ошибки не возникает

или дело в том как yandex отвечает на запрос?

**Comment by aksenov** [comment]
До Яндекса дело не доходит (java.net.ConnectException).
Соединение с Интернетом идет через корпоративный прокси. В консоли выставляются переменные http_proxy и https_proxy, запускается lein run. Leiningen скачивает библиотечки с clojars, что косвенно показывает возможность соединения с интернетом, но запросы от сервера к Яндексу уже не проходят. Это из-ща особенности реализации httpkit.client, если я не ошибаюсь.

**Comment by tkachenko1503** [comment]
кажется slurp должен нормально справляться
